### ISSUE TITLE
Incorporate charting view into app 

### ISSUE THREAD

**Issue by gdegas** [edyza/Edyza-grommet-dash#1]
## Motivation
need sum charts

## Tasks
- [x] Add a link to the side navbar
- [x] install project dependencies that are needed.
- [x] Figure out how to render the component when the link is clicked
- [ ] Install MQTT library and see if you can get console logs for messages coming in
- [ ] import chart components from other library
